module.exports = {
    titleBlogPage: 'Read Our Blog Posts, Updates and Tutorials',
    titleLoginPage: 'Login / Telnyx Customer Portal',
    titleIotSimCardsPage: 'IoT SIM Cards for Global Connectivity | Telnyx',
    titleSignUpPage: 'Sign Up | Telnyx',
    titleLoginWithMicrosof: 'Sign in to your account',
    titleOomaPage: 'Ooma Provides Unique Voice and Messaging Solutions',
    titleTalkToAnExpertPage: 'Contact a member of the Telnyx sales team',
    titlePricingPage: 'Pricing / Telnyx Customer Portal',
    titleReportAbusePage: 'Report Abuse Made On The Telnyx Platform',
    titlePrivacyPolicyPage: 'Detailed Information on the Privacy Policy at Telnyx',
    titleDevelopersPage: 'Telnyx Developers',
    titleCookiePolicyPage: 'Detailed information on the cookie policy at Telnyx',
    titleTwitterPage: 'Telnyx (@telnyx) / Twitter',
    titleVideoRoomsPage: 'Video Rooms / Telnyx Customer Portal',
    titleDemoAppPage: 'Demo App / Telnyx Customer Portal',
    titleHomePage: "title ? title + ' / Telnyx Customer Portal' : 'Telnyx Customer Portal'",
    urlVideoRoomPage: '/video-rooms',
    urlHomePage: '/home',
    urlTwitter: 'twitter.com',
    validEmailForLogin: 'testtestunia@gmail.com',
    validPasswordForLogin: 'qwertyU789!!',
    invalidWebhookURL: 'Invalid',
    videoRoomName: 'Name',
    email: 'test@gmail.com',
    fullName: 'Ivan Ivanovych',
    password:'sdfGHJKL236!@QQQQnn12',
    lessCharacterPassword: '123', 
    addCharactersInPassword: '12345678910',
    number: '(888) 980 9750'
    
}